### ISSUE TITLE
LuaListBoxEx Git-64b883957cfd8 при запуске moon-примера выводится ошибка

### ISSUE THREAD

**Issue by VictorVG** [trexinc/evil-programmers#26]
Поставил на пробу. Понравилось, с testlist.lua всё работает, выводится диалог:

![testlistlua](https://cloud.githubusercontent.com/assets/906886/20115053/d4a744ea-a607-11e6-83af-355f9369915a.png)

а в его MoonScript варианте при запуске выводится сообщение об ошибке:

> LuaMacro
> 
> LuaListBoxEx\Samples\testlist.moon:3:
> unexpected symbol near '63'

примеры для теста лежат отдельно, запускаются по ассоциации lua:@"!=\!.!". 

Вопрос: что мне нужно поправить чтобы устранить данную ошибку? Я предполагаю что ошибка сидит у меня. Тестировал на Far 3.0 b4833 r14594 x64 под Win7 SP1 x64.

**Comment by shmuz** [comment]
Ассоциация для moon-файлов должна быть `moon:@"!=!.!"`.

**Comment by VictorVG** [comment]
Спасибо! Частью правил, на срверах поправлю как до своей машины доберусь. У менясидела неверная ассоциация. Поменял по подсказке - всё работает. Закрываю инц как решённый, а на серверах уже к вечеру поправлю - удалённое управление у меня специально отключено.

**Comment by VictorVG** [comment]
P.S.

Писал корабля по ЙОТЕ, вдогонку у ноута KBD залита - вышло забавно, сразу попытался исправить - ага, разбегись - связь рвётся, а мы идём потихоньку пока соляра в танках хватает.:)
