### ISSUE TITLE
Большая внутренняя задержка в алгоритме LuaEditorSettingsCore

### ISSUE THREAD

**Issue by VictorVG** [trexinc/evil-programmers#48]
Для проверки использовано:

Far без дополнительных макросов и скриптов с плагином LuaMacro, наличие иных плагинов не обязательно;

Простой тест-скрипт бенчмарк запускаемый из командной строки LuaMacro или по ассоциации Lua,Moon -> lua:@!=\!.!  :

```
local a = Far.UpTime; far.MacroLoadAll(); msgbox("",(Far.UpTime - a)/1000)

mmode(1,0); local t=Far.UpTime; for i=1,1000 do Keys"Tab" end far.Message(Far.UpTime-t)
```

Методика проверки:

1. Запускаем бенчмарк до установки LuaEditorSettingsCore, фиксируем время выполнения;
2. Ставим LuaEditorSettingsCore и повторяем пункт 1.

У меня на машине с i7-2600/z68/DDR3-1600 9,0-9-9-27 Cr2 получилось, что время выполнения бенчмарка при наличии в наборе скриптов LuaEditorSettingsCore возрастает в среднем примерно на 0,300 сек - без дополнительных скриптов в серии из 10 экспериментов время выполнения бенчмарка составило 0,002, после его установки в качестве единственного скрипта оно колеблется около значения 0,3 ± статистичекая погрешность, т.е выходит что в алгоритме в скрипте где-то возникает задержка.

Так же я сделал ряд экспериментов и в условиях использования всего набора применяемых мной скриптов вносящего в результат бенчмарка зависящую от текущей загрузки ЦП задержку от 0,076 до 0,097 на скриншоте слева и с добавлением в набор LuaEditorSettngsCore - скриншот справа :

![1](https://user-images.githubusercontent.com/906886/82757500-8571f400-9de9-11ea-975b-d9977c278b9e.png)

а так же на минимальной тест-копии только с единственным скриптом LuaEditorSettingsCore:

![2](https://user-images.githubusercontent.com/906886/82757888-ed293e80-9deb-11ea-8971-3a0a9d4a1547.png)

и вообще без скриптов:

![3](https://user-images.githubusercontent.com/906886/82757921-0f22c100-9dec-11ea-9a66-9987d6067fa5.png)

P.S.

Я хотел использовать LuaEditorSettingsCore в качестве замены плагина [ESC] который уже достал меня своими падениями в момент сохранения редактируемых файлов, но пока приходится писать свой скрипт с "простыней" из почти сорока (на данный момент) блоков установки начальных параметоров редактора под разные типы файлов....

**Comment by zg0** [comment]
я попробовал у себя. без LESC 0.1 с, с — колеблется от 0.25 до 0.35. сделал так:
`local a = Far.UpTime; for ii=1,10 do far.MacroLoadAll(); end msgbox("",(Far.UpTime - a)/10000)`
стало где-то 0.28. т.е. у меня скрипт загружается 0.18 с. где-то половина из этого editorsettings_base.moon. половина из этой половины — highlite. видимо, чтобы lpeg скомпилировал свои паттерны — нужно время. вторая половина — классы. у меня файл с 50 пустыми классами добавляет 0.03–0.04 секунды. причин не знаю. можно сделать без классов, но по мне 0.04 с при загрузке не такая уж большая плата за удобство. опять же это мускрипт — его надо ещё в луа оттранслировать.
да, скорее всего, если переписать на чистом луа, запихнуть всё в один файл, время на какую-нибудь треть сократится. может быть в два раза. но я лично потеряю в удобстве. а так, если есть какие-то конкретные предложение по оптимизации, говорите — я не утверждаю, что там всё идеально. просто так это всё выглядит как: ваш скрипт работает долго, потому что мне кажется, что он плохо старается и мог бы быстрее.

**Comment by shmuz** [comment]
> да, скорее всего, если переписать на чистом луа, запихнуть всё в один файл, время на какую-нибудь треть сократится. может быть в два раза. но я лично потеряю в удобстве.

Для разработчика, если он часто играется с кодом скрипта, имеет смысл держать его в оригинальном виде (moonscript). А для пользователя, который обновляет скрипт раз в кои веки, можно скомпилировать его в Lua и поместить в свои скрипты как Lua-файл.

**Comment by VictorVG** [comment]
Ага, тогда, допустимо. А то, то, что я сейчас пишу это простыня из как минимум трёх десятков отдельных небольших обработчиков событий которые выставляют стартовые параметры редактора. Сначала думал всё запихнуть в один и раскидать по отдельным If Then Else -выходит бестолково, вот и тяну в надежде что не придётся это дописывать.:) 

А кстати, как скомпилировать скрипт в Lua? Я с этим ни разу не встречался и не представляю как это сделать?

**Comment by zg0** [comment]
и до кучи. в скрипте при старте читаются две настройки. это на моей машине 0.01–0.015 с. т.е. 10%-15% процентов от времени инициализации всех остальных моих скриптов. так что это не этот скрипт тормозит при старте, а остальные ничего при старте не делают.
как скрипт в луа скомпилировать, можно тут посмотреть: https://github.com/FarGroup/FarManager/blob/master/plugins/luamacro/luasdk/build_moonscript.zip

**Comment by VictorVG** [comment]
Спасибо огромное! А то я поскольку никогда с этим не сталкивался не знал с какого угла решать эту задачу.
